KTB-06: Add extension "filter" in task  No. 6
RomkaGra4/KotlinTelegramBot pull request #4
Opened 2024-07-17 20:28 UTC by RomkaGra4

Приветствую!) 

Немного завис на этом этапе. Я добавил extension функцию filter. В задании сказано "для словаря", следовательно как я понял функция для класса Flie.

Если это так, то как мне брать инфо о полном кол-ве слов в словаре?

Или я вообще неправильно понят задание?))) 
Подскажи пожалуйста :)

2024-07-18 07:01 UTC, danelyan requested changes

2024-07-18 07:01 UTC, danelyan commented on src/main/kotlin/Main.kt
> +fun File.filter() {
> Приветствую!)
> 
> Немного завис на этом этапе. Я добавил extension функцию filter. В задании сказано "для словаря", следовательно как я понял функция для класса Flie.
> 
> Если это так, то как мне брать инфо о полном кол-ве слов в словаре?
> 
> Или я вообще неправильно понят задание?)))
> Подскажи пожалуйста :)

Неправильно понял )
Функция `filter()` уже есть у списков. Нужно применить ее к списку слов словаря, и отфлитровать выученные слова.

Давай переименуем этот метод в showStatistics(), внутри применим filer {}, чтобы потом взять размер полученного списка выученных слов и использовать для подсчета статистики

2024-07-20 20:19 UTC, RomkaGra4 commented
Похоже что я в 4-м задании пропустил пару пунктов, из-за чего не понимал как двигаться дальше в 6-м т.к. не создал ранее dictionary с которым уже работаю через "showStatistics()". :))) В общем кайф словил, когда капнул в предыдущее задание и понял "где собака зарыта" :))))

В общем вроде все ок. За исключением свойства "correctAnswersCount". Не понял, оно так и должно быть по умолчанию ноль и мы его потом доработаем? Или сейчас уже оно должно изменяться каким-то образом?

2024-07-23 19:10 UTC, danelyan requested changes
> В общем вроде все ок. За исключением свойства "correctAnswersCount". Не понял, оно так и должно быть по умолчанию ноль и мы его потом доработаем? Или сейчас уже оно должно изменяться каким-то образом?

Позже доработаем ))
Но мелкий коммент надо поправить

2024-07-23 19:10 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        it.correctAnswersCount >= 3
давай 3 вынесем в константы

2024-07-27 19:01 UTC, danelyan requested changes

2024-07-27 19:01 UTC, danelyan commented on src/main/kotlin/Main.kt
> +    const val MAX_COUNT = 3
плохое название константы. "Максимальный счет"? Даже в контексте не совсем понятно что за цифра

2024-07-27 19:01 UTC, danelyan commented on src/main/kotlin/Main.kt
>      wordsFile.appendText("good morning|доброе утро\n")
тут нам уже не нужно заполнять words.txt, пригодится позже, чтобы сохранять измененные значения.
Давай просто положим файл words.txt со словами в корень проекта и запушим

2024-07-27 19:01 UTC, danelyan commented on src/main/kotlin/Main.kt
> +    val lines: MutableList<String> = wordsFile.readLines().toMutableList()
Так ты расходуешь больше оперативной памяти в моменте.
Давай сразу для каждой строки делать маппинг в слово:
```Kotlin
wordsFile.readLines().map {
// ...
}
```

2024-07-27 19:01 UTC, danelyan commented on src/main/kotlin/Main.kt
> +fun MutableList<Word>.showStatistics() {
Большого смысла нет делать показ статистики функцией расширения. Это прикольно, но сбивает с толку немного. Можешь оставить, потом все равно эта часть будет переделываться

2024-08-03 21:40 UTC, RomkaGra4 commented on src/main/kotlin/Main.kt
> +fun MutableList<Word>.showStatistics() {
Тогда эту часть оставить нетронутой? Или что предлагаешь с ней сделать?)

2024-08-04 15:18 UTC, danelyan approved these changes

2024-08-04 15:18 UTC, danelyan commented on src/main/kotlin/Main.kt
> +fun MutableList<Word>.showStatistics() {
Пока оставь. Когда будем выносить всю логику в отдельный класс оно переделается

2024-08-04 17:31 UTC, merged