KTB-07: Completed tasks for stage 07
RomkaGra4/KotlinTelegramBot pull request #5
Opened 2024-08-15 19:40 UTC by RomkaGra4

Привет! Немного выпал из обучения. Сейчас вернулся и набираю скорость :) 
Немного туплю с выполнением данного таска. Не понимаю как увеличивать correctAnswersCount при корректном выборе правильного ответа... Или это будет в задании позднее? Жду обратную связь :)

2024-08-16 06:42 UTC, kaznikit commented
> Привет! Немного выпал из обучения. Сейчас вернулся и набираю скорость :) Немного туплю с выполнением данного таска. Не понимаю как увеличивать correctAnswersCount при корректном выборе правильного ответа... Или это будет в задании позднее? Жду обратную связь :)

Привет! В предыдущих заданиях мы создавали текстовый файл формата `"слово|перевод|количество правильных ответов"`. Поэтому нужно считывать количество из файла, а затем при корректном ответе перезаписывать

2024-08-16 06:47 UTC, kaznikit requested changes

2024-08-16 06:47 UTC, kaznikit commented on src/main/kotlin/showStatistics.kt
> +fun MutableList<Word>.showStatistics() {
Давай не будем выносить эту функцию в отдельный файл, можно пока оставить в Main

2024-08-16 06:47 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +    println("Выбери правильный вариант перевода: " + answers.random().englishText)
Давай использовать интерполяцию для вывода

2024-08-16 06:47 UTC, kaznikit commented on src/main/kotlin/Main.kt
>      while (true) {
Давай также добавим функцию `loadDictionary` для загрузки словаря

2024-08-16 14:29 UTC, RomkaGra4 commented on src/main/kotlin/showStatistics.kt
> +fun MutableList<Word>.showStatistics() {
Окей. Возвращаю в Main

2024-08-16 17:04 UTC, RomkaGra4 commented on src/main/kotlin/Main.kt
>      while (true) {
Подскажи, а какой функционал у этой функции будет? Если в вариантах 1 и 2 уже функции learnWords и showStatistics обращаются к словарю?

2024-08-17 12:02 UTC, kaznikit commented on src/main/kotlin/Main.kt
>      while (true) {
в нее стоит вынести логику чтения/создания файла. возвращать она будет словарь - `List<Word>` и далее мы уже с ним будем работать

2024-08-17 12:03 UTC, kaznikit requested changes

2024-08-17 12:03 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +    TODO("Not yet implemented")
отписал в коммент что сюда стоит вынести логику чтения файла и формирования словаря

2024-08-18 18:18 UTC, RomkaGra4 commented on src/main/kotlin/Main.kt
> +    TODO("Not yet implemented")
Okey

2024-08-19 05:21 UTC, kaznikit approved these changes

2024-09-04 16:26 UTC, merged