KTB-08: Completed task 1, 2 and 3 for stage 08
RomkaGra4/KotlinTelegramBot pull request #7
Opened 2024-09-05 19:26 UTC by RomkaGra4

Приветствую!)

В общем 2 момента, на который я "провисаю"... И еще один вопрос (3) который я не могу разобрать:

Я не совсем понял как должна действовать функция saveDictionary(). Согласно ТЗ я её сделал, но она не имеет как такового функционала потому что я не понял куда именно должно происходить сохранение.

Когда я пробегал по "Вопрос-ответ", то заметил что на при наборе "3" в одном из элементов словаря (например правильно отвечал 3 раза на слове dog) у меня оставшиеся слова которые идут по списку (кошка, доброе утро) - не появлялись в будущих вопросах. А как только первый элемент (слово "привет") набирал 3 - то ошибка происходила на строке №53. Получается на этапе KTB-07 я допустил ошибку при создании "проверки на кол-во правильных ответов"?
Или все по плану и мы такие ошибки будем фиксить в "KTB-10 Протестировать функционал и пофиксить баги" ? ))

Еще момент, в словаре у меня 5 словесных пар. А по ТЗ нам необходимо использовать 4 варианта ответа. Тем самым у меня с помощью метода take() обрезается остаток словаря. Подскажи, в данном случае нужно перезаписывать список, исключая слова на которые мы уже ответили 3 раза?

Жду обратную связь :)

2024-09-06 16:49 UTC, kaznikit commented
> Приветствую!)
> 
> В общем 2 момента, на который я "провисаю"... И еще один вопрос (3) который я не могу разобрать:
> 
> Я не совсем понял как должна действовать функция saveDictionary(). Согласно ТЗ я её сделал, но она не имеет как такового функционала потому что я не понял куда именно должно происходить сохранение.
> 
> Когда я пробегал по "Вопрос-ответ", то заметил что на при наборе "3" в одном из элементов словаря (например правильно отвечал 3 раза на слове dog) у меня оставшиеся слова которые идут по списку (кошка, доброе утро) - не появлялись в будущих вопросах. А как только первый элемент (слово "привет") набирал 3 - то ошибка происходила на строке №53. Получается на этапе KTB-07 я допустил ошибку при создании "проверки на кол-во правильных ответов"? Или все по плану и мы такие ошибки будем фиксить в "KTB-10 Протестировать функционал и пофиксить баги" ? ))
> 
> Еще момент, в словаре у меня 5 словесных пар. А по ТЗ нам необходимо использовать 4 варианта ответа. Тем самым у меня с помощью метода take() обрезается остаток словаря. Подскажи, в данном случае нужно перезаписывать список, исключая слова на которые мы уже ответили 3 раза?
> 
> Жду обратную связь :)

привет!

по поводу функции сохранения словаря. тебе нужно открывать существующий файл `val wordsFile: File = File("words.txt")`, далее создавать обновленный контент и записывать его в файл. 

баг с ответами давай оставим до 10 урока) помогу если не получится разобраться самому)

в случае когда не осталось слов для вариантов ответа, давай добавлять варианты из уже выученных слов) чтобы для выбора ответа у нас всегда было 4 слова

2024-09-06 16:49 UTC, kaznikit requested changes

2024-09-06 16:49 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +}
отписал в коммент)

2024-09-11 09:11 UTC, kaznikit requested changes

2024-09-11 09:11 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +        wordsFile.writeText(answers.toString())
мы же должны записывать в словарь слова с разделителем |. сейчас ты просто запишешь список слов, но считать мы его в дальнейшем не сможем

2024-09-12 08:54 UTC, kaznikit requested changes

2024-09-12 08:54 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +fun saveDictionary(answers: List<Word>): MutableList<Word> {
эта функция должна только сохранять новые данные в файл, зачем она возвращает список слов? в предыдущем комменте я говорил о том, что мы должны писать в файл с разделителями, таким образом:
```
private fun saveDictionary(answers: List<Word>) {
        val wordsFile: File = File("words.txt")
        val fileContent = answers.joinToString("\n") { "${it.englishText}|${it.russianText}|${it.correctAnswersCount}" }
        wordsFile.writeText(fileContent)
    }
```

2024-09-12 12:52 UTC, RomkaGra4 commented on src/main/kotlin/Main.kt
> +fun saveDictionary(answers: List<Word>): MutableList<Word> {
Ой, точно! Спасибо что пояснил :) А я и не понял - зачем дважды делать одну и ту же функцию))

2024-09-13 06:52 UTC, kaznikit approved these changes

2024-09-13 06:52 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +    wordsFile.writeText(answers.toString())
сейчас аппрув, но эта функция не нужна, так как сначала мы в файл запишем список слов, а далее запишем его же, только с разделителем

2024-09-13 08:42 UTC, merged